name: Deploy Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /home/vinh/project/Banhang
          git fetch origin main
          git reset --hard origin/main
          docker compose down
          docker compose up -d --build
